[build]
  command = "npm install && npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Переменные окружения (можно переопределить в Netlify Dashboard)
[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyB0AxrtCw0QYxEHbxGExVfRlDoz0OGtfTI"
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "playflon.firebaseapp.com"
  NEXT_PUBLIC_FIREBASE_PROJECT_ID = "playflon"
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "playflon.firebasestorage.app"
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "309141897476"
  NEXT_PUBLIC_FIREBASE_APP_ID = "1:309141897476:web:d117f2a297ea06d1a61051"

